server:
  address: "0.0.0.0:42901"

database:
  conn_str: "user=task_tracker dbname=task_tracker_test sslmode=disable"
  #  log_levels: ["debug", "error", "trace", "info", "warn"]
  log_levels: ["error", "info", "warn"]

git:
  webhook_secret: "very_secret_secret"
  # Github: sha1, Gogs: sha256
  webhook_hash: "sha256"
  # Github: 'X-Hub-Signature', Gogs: 'X-Gogs-Signature'
  webhook_sig_header: "X-Gogs-Signature"

log:
  # panic, fatal, error, warn, info, debug, trace
  level: "trace"

session:
  cookie_name: "tt"
  expiration: "25m"

monitoring:
  snapshot_interval: "60s"
  history_length: "4h"
