server:
  address: "0.0.0.0:42901"

database:
  conn_str: "user=task_tracker dbname=task_tracker_test sslmode=disable"
  log_levels: ["debug", "error"]

git:
  webhook_secret: "very_secret_secret"
  # Github: sha1, Gogs: sha256
  webhook_hash: "sha1"
  # Github: 'X-Hub-Signature', Gogs: 'X-Gogs-Signature'
  webhook_sig_header: "X-Hub-Signature"

log:
  # panic, fatal, error, warn, info, debug, trace
  level: "trace"

session:
  cookie_name: "tt"
  expiration: "25m"
